<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Vijay" failures="3" tests="8" name="TestDemo1" time="0.103" errors="0" timestamp="2023-07-26T02:31:27 IST">
  <testcase classname="com.qa.testng.listeners.TestngDemo1" name="testcase1" time="0.016"/>
  <testcase classname="com.qa.testng.listeners.TestngDemo1" name="testcase2" time="0.016"/>
  <testcase classname="com.qa.testng.listeners.TestngDemo2" name="testcase5" time="0.016"/>
  <testcase classname="com.qa.testng.listeners.TestngDemo2" name="testcase6" time="0.002"/>
  <testcase classname="com.qa.testng.listeners.TestngDemo2" name="testcase8" time="0.008">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at com.qa.testng.listeners.TestngDemo2.testcase8(TestngDemo2.java:38)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testcase8 -->
  <testcase classname="com.qa.testng.listeners.TestngDemo2" name="testcase7" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.testng.listeners.TestngDemo2.testcase7(TestngDemo2.java:29)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testcase7 -->
  <testcase classname="com.qa.testng.listeners.TestngDemo1" name="testcase3" time="0.033">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.testng.listeners.TestngDemo1.testcase3(TestngDemo1.java:29)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testcase3 -->
  <testcase classname="com.qa.testng.listeners.TestngDemo1" name="testcase4" time="0.0">
    <skipped/>
  </testcase> <!-- testcase4 -->
</testsuite> <!-- TestDemo1 -->
